/* AUTO-GENERATED by the revun-category-faqs workflow (2026-06-04). Do not hand-edit. */
export const categoryFaqs: Record<string, { q: string; a: string }[]> = {
  "property-management-software": [
    {
      "q": "What does property management software actually do?",
      "a": "Property management software brings together the tools landlords and managers need to run rentals in one place, typically covering leasing, rent collection, maintenance tracking, tenant screening, and financial reporting. Instead of juggling spreadsheets, separate payment apps, and email threads, everything lives in a single dashboard. Revun is built around this all-in-one model, so leases, payments, maintenance requests, and communications are connected from day one."
    },
    {
      "q": "How much does property management software cost?",
      "a": "Pricing models vary widely. Some platforms charge a percentage of rent collected, others charge per unit per month, and a few offer free tiers for very small portfolios. Revun uses flat per-door pricing so your cost scales predictably as you add units, and portfolios of one or two units can use the platform at no charge to get started."
    },
    {
      "q": "Does property management software work in Canada as well as the US?",
      "a": "Many platforms are US-only or treat Canadian landlords as an afterthought, which creates gaps in payment processing and lease compliance. Revun is built for both the US and Canada, so landlords and property managers on either side of the border get full feature access including rent collection, screening, and accounting without workarounds."
    },
    {
      "q": "What is the easiest property management software to switch to if I am already using another platform?",
      "a": "The main friction when switching is migrating tenant records, lease dates, and payment history. Look for a platform that lets you import data in bulk and does not lock you into long-term contracts during the transition. Revun keeps onboarding straightforward with a clean setup flow, and because pricing is per door rather than per seat, you can add your portfolio incrementally without a big upfront commitment."
    },
    {
      "q": "Can property management software handle both residential and small commercial units?",
      "a": "Most full-featured platforms support residential properties well, and a growing number extend to small commercial or mixed-use portfolios. The key features to look for are flexible lease terms, customizable charge types, and maintenance workflows that are not rigidly tied to residential templates. Revun covers these use cases within its core feature set, making it practical for landlords managing a mix of property types."
    },
    {
      "q": "Does property management software include tenant screening and background checks?",
      "a": "Screening is built into most modern platforms, though the depth of the check and the cost per report varies. Good screening should cover credit, criminal history, and eviction records, and ideally be initiated directly from the rental application without the manager having to log into a separate service. Revun includes screening as part of the platform so the applicant flow connects directly to lease creation once you approve a tenant."
    }
  ],
  "ai-property-management-software": [
    {
      "q": "What does AI property management software actually do?",
      "a": "AI property management software automates the repetitive work landlords and property managers deal with daily, including screening applicants, sending rent reminders, routing maintenance requests, and flagging lease renewals before they lapse. The best platforms combine these AI features with built-in tools for leasing, payments, accounting, and tenant communications so everything lives in one place. Revun is built around this idea, giving you an all-in-one dashboard that handles the full property management lifecycle without stitching together separate apps."
    },
    {
      "q": "How much does AI property management software cost?",
      "a": "Pricing varies widely. Some platforms charge a percentage of rent collected, others bill per unit per month, and a few offer a free tier for small portfolios. Revun uses flat per-door pricing so your costs stay predictable as you scale, and it is completely free for landlords managing one or two units. That makes it practical to start without any upfront commitment and upgrade only when your portfolio grows."
    },
    {
      "q": "Does AI property management software work in Canada as well as the US?",
      "a": "Many property management tools are built exclusively for the US market, which creates compliance gaps for Canadian landlords dealing with provincial lease rules and local payment norms. Revun is designed to serve property owners and managers across both the US and Canada, so the platform accounts for cross-border workflows whether you operate in a single market or both. You get the same feature set regardless of where your properties are located."
    },
    {
      "q": "Who is AI property management software best suited for?",
      "a": "It works well for independent landlords who want to stop managing everything through spreadsheets and email, as well as for growing portfolio managers who need automation to scale without adding headcount. The tools are especially valuable if you handle tenant screening, maintenance coordination, and rent collection yourself and want a system that keeps all of it organized. Revun is built for both sides of that spectrum, with a free plan for small landlords and a scalable paid tier for managers running larger portfolios."
    },
    {
      "q": "Can I switch to a new property management platform without losing my data?",
      "a": "Switching platforms feels risky, but most modern AI property management tools including Revun support data import for your tenant records, lease dates, and payment history so you are not starting from zero. The onboarding process typically involves exporting a spreadsheet or CSV from your current tool and mapping it into the new system. The harder part is usually retraining your workflow, which is why platforms with dedicated onboarding support make the transition noticeably smoother."
    },
    {
      "q": "Does property management software handle maintenance requests and vendor communication?",
      "a": "Yes, and this is one of the areas where AI features add the most day-to-day value. Tenants submit requests through a portal, the platform categorizes and prioritizes them, and you can assign work orders directly to vendors from the same interface. Revun has maintenance tracking built in alongside leasing, payments, and communications, so you are not jumping between apps to close out a single repair ticket."
    }
  ],
  "property-management-operating-system": [
    {
      "q": "What is a property management operating system and how is it different from basic landlord software?",
      "a": "A property management operating system is an all-in-one platform that connects every workflow in your portfolio, from leasing and tenant screening to rent collection, maintenance tracking, communications, and accounting, in one place. Basic landlord software typically handles one or two of those functions, forcing you to stitch together separate tools and re-enter data across them. Revun is built as a full operating system, so every action updates a single record rather than living in a silo."
    },
    {
      "q": "How much does a property management operating system cost per unit per month?",
      "a": "Pricing models vary widely: some platforms charge a percentage of rent collected, others bill per seat, and a growing number use flat per-door pricing that scales predictably as your portfolio grows. Revun uses flat per-door pricing with no percentage-of-rent fees, and units one and two are completely free, making it approachable for landlords who are just getting started."
    },
    {
      "q": "Does a property management operating system work for landlords in both the US and Canada?",
      "a": "Many platforms are built exclusively for US markets and lack support for Canadian banking rails, provincial lease requirements, or CAD currency. Revun is designed for both US and Canadian property owners, handling currency, compliance considerations, and localized workflows across both countries without requiring separate accounts or workarounds."
    },
    {
      "q": "What features should I look for in a property management operating system?",
      "a": "The core features worth evaluating are tenant screening, online leasing and e-signatures, automated rent collection, a maintenance request and work order system, two-way tenant messaging, and owner-ready accounting and reporting. You also want to check whether those features are natively integrated or just third-party widgets bolted on, since deep integration eliminates double entry and missed updates. Revun includes all of the above as built-in modules on a single platform rather than a marketplace of add-ons."
    },
    {
      "q": "How hard is it to switch from my current software to a new property management operating system?",
      "a": "Switching friction usually comes from three things: migrating existing tenant and lease data, training your team on new workflows, and re-connecting any integrations you depend on. Most modern platforms, including Revun, offer onboarding support and importable templates to move your unit, tenant, and payment history over without starting from scratch. The cleaner your current data, the faster the transition tends to go."
    },
    {
      "q": "Is a property management operating system worth it if I only manage a small portfolio?",
      "a": "Small portfolio landlords often benefit the most from consolidating tools because the time cost of juggling spreadsheets, separate payment apps, and email threads is disproportionately high relative to rent collected. A purpose-built system automates rent reminders, tracks maintenance from request to resolution, and keeps a clean paper trail without requiring a full-time property manager. Revun is free for one to two units specifically so smaller landlords can start with a professional-grade system before they need to pay anything."
    }
  ],
  "property-operations-software": [
    {
      "q": "What does property operations software actually do?",
      "a": "Property operations software brings together the tools landlords and property managers use every day into one connected platform, covering leasing, rent collection, maintenance tracking, tenant screening, communications, and accounting. Instead of juggling separate apps for each function, everything updates in real time from a single dashboard. Revun is built this way so your data flows automatically across every module without manual entry or re-keying."
    },
    {
      "q": "How much does property operations software cost?",
      "a": "Most platforms charge either a flat monthly fee per unit (door pricing) or a percentage of rent collected, which can get expensive as your portfolio grows. Revun uses flat per-door pricing so your cost is predictable, and the platform is free for landlords managing one or two units. You can find current tier details on the Revun pricing page without having to talk to sales."
    },
    {
      "q": "Does property operations software work in Canada as well as the United States?",
      "a": "Many platforms are US-only or handle Canadian leases as an afterthought, which creates compliance headaches for landlords operating across the border. Revun is built for both the US and Canada, supporting rent payments, lease workflows, and tenant communications in both markets. If you manage properties in multiple cities on both sides of the border, everything runs inside one account."
    },
    {
      "q": "Who is property operations software for, small landlords or large property management companies?",
      "a": "The best platforms scale to fit both, though pricing and feature depth vary a lot. Revun works for individual landlords with a handful of units (including a free plan for one or two doors) all the way up to property management companies handling large multi-family or mixed portfolios. The same tools for screening, leasing, maintenance, and accounting are available at every tier, not gated to enterprise tiers."
    },
    {
      "q": "Can I switch to a new property operations platform without losing my existing lease and payment data?",
      "a": "Switching feels daunting, but modern platforms support CSV or structured data imports for leases, tenant records, and payment history so you are not starting from zero. Revun includes onboarding support to help you migrate existing unit and tenant data before you go live. Most landlords are able to complete the switch without any gap in rent collection or maintenance tracking."
    },
    {
      "q": "What integrations does property operations software typically include?",
      "a": "Common integrations cover online listing syndication, electronic payment processors, accounting exports like QuickBooks, background and credit screening bureaus, and maintenance vendor portals. Revun has these core integrations built in natively rather than requiring third-party connectors, so there is no extra subscription needed to list a vacancy, screen an applicant, or reconcile your books."
    }
  ],
  "leasing-software": [
    {
      "q": "What does leasing software for property managers actually do?",
      "a": "Leasing software handles the full rental lifecycle from listing and applications through lease signing and move-in. Most platforms combine tenant screening, digital lease generation, and payment collection in one place so managers are not jumping between tools. Revun covers all of that alongside maintenance requests, owner accounting, and tenant communications in a single dashboard."
    },
    {
      "q": "How much does property management leasing software cost?",
      "a": "Pricing models vary widely. Some platforms charge a percentage of rent collected (typically 2 to 4 percent), others bill a flat monthly fee per unit ranging from $1 to $3 per door, and a few offer a free tier for small portfolios. Revun uses flat per-door pricing with no percentage cuts, and portfolios of one or two units can use the platform at no charge."
    },
    {
      "q": "Does property management software work for both US and Canadian landlords?",
      "a": "Not all platforms support Canadian lease requirements, payment rails, or provincial-specific compliance. Managers in Canada need software that handles CAD currency, local lease forms, and e-transfer compatible payment processing. Revun is built for US and Canadian property managers, so both markets get full feature access without workarounds."
    },
    {
      "q": "Can leasing software handle tenant screening and background checks?",
      "a": "Most modern property management platforms include integrated screening that pulls credit reports, criminal history, and eviction records directly inside the application flow. This keeps everything in one record rather than managing screening results from a separate service. Revun includes screening as part of the leasing workflow so managers can review applicants and sign leases without leaving the platform."
    },
    {
      "q": "How hard is it to switch property management software if I already use something else?",
      "a": "The main effort in switching is migrating tenant records, lease dates, and payment history into the new system, which most platforms either import via CSV or handle through an onboarding call. The longer you wait with a growing portfolio, the more data there is to move, so earlier switches are generally smoother. Revun's onboarding process is designed for managers coming from tools like AppFolio, Buildium, or even spreadsheets."
    },
    {
      "q": "Is there a free leasing software option for landlords with just a few units?",
      "a": "Several platforms offer limited free tiers, but they often restrict features like online payments, maintenance tracking, or lease storage behind a paid upgrade. A genuinely useful free tier should cover applications, screening, and at least basic lease management. Revun is free for landlords managing one or two units with no feature restrictions, making it practical for small portfolios rather than just a stripped-down trial."
    }
  ],
  "brokerage-software": [
    {
      "q": "What does real estate brokerage software actually do?",
      "a": "Real estate brokerage software centralizes the tools brokers and property managers use every day, covering leasing, rent collection, maintenance tracking, tenant screening, communications, and accounting in one place. Instead of juggling separate apps for each task, everything runs from a single dashboard. Revun is built around this model so brokers managing portfolios across the US and Canada can handle the full property lifecycle without switching platforms."
    },
    {
      "q": "How much does real estate brokerage software typically cost?",
      "a": "Pricing varies widely: some platforms charge a percentage of rent collected, others use a flat monthly fee per unit, and a few add setup or onboarding costs on top. Flat per-door pricing tends to be the most predictable for growing portfolios. Revun uses flat per-door pricing and is free for landlords managing one or two units, making it accessible whether you are just starting out or scaling up."
    },
    {
      "q": "Can real estate brokerage software handle both US and Canadian properties?",
      "a": "Most platforms are built exclusively for one country, which creates headaches around currency, lease law differences, and provincial or state reporting requirements. If your portfolio spans the border, you need software designed to handle both markets from the start. Revun supports landlords and brokers across the US and Canada, so you can manage properties on both sides of the border without workarounds."
    },
    {
      "q": "Is real estate brokerage software hard to switch to if I am already using something else?",
      "a": "Switching property management software feels daunting mostly because of tenant data, lease history, and payment records, but modern platforms have streamlined imports to reduce the friction. The key questions to ask are whether your existing data can be exported cleanly and whether the new platform offers onboarding support. Revun is designed to get portfolios up and running quickly, and flat pricing means there is no financial penalty for starting mid-portfolio cycle."
    },
    {
      "q": "What integrations should I look for in real estate brokerage software?",
      "a": "The most valuable integrations are with accounting tools like QuickBooks, listing syndication networks, payment processors, and e-signature platforms so your workflow stays connected end to end. You should also look for maintenance request portals that tenants can access without calling the office. Revun bundles payments, maintenance, and communications natively so fewer third-party integrations are needed in the first place, which reduces both cost and setup time."
    },
    {
      "q": "Who is real estate brokerage software best suited for?",
      "a": "It is most useful for property managers, real estate brokers overseeing rental portfolios, and independent landlords who have outgrown spreadsheets or single-purpose apps. The right fit depends on portfolio size, whether you manage residential or commercial units, and how much of the workflow you want automated. Revun is built for operators at any scale, from a landlord with a couple of units all the way to brokers managing hundreds of doors across multiple markets."
    }
  ],
  "maintenance-management-software": [
    {
      "q": "What does property maintenance management software actually do?",
      "a": "Property maintenance management software centralizes how landlords and property managers receive, assign, track, and close out repair requests across their portfolio. The best platforms tie maintenance directly into tenant communications, vendor payments, and accounting so nothing falls through the cracks. Revun handles all of this in one place, giving owners a live view of every open work order without juggling spreadsheets or separate apps."
    },
    {
      "q": "How much does property maintenance management software cost?",
      "a": "Pricing models vary widely: some tools charge per user, others charge a flat monthly fee, and others use a per-door rate that scales with your portfolio. Revun uses flat per-door pricing so your cost grows predictably as you add units, and it is completely free for landlords managing 1 or 2 units. There are no hidden setup fees or module paywalls since maintenance, leasing, payments, and accounting are all included."
    },
    {
      "q": "Does property maintenance management software work for both US and Canadian landlords?",
      "a": "Not all platforms support both markets since lease law, payment rails, and currency handling differ between the US and Canada. Revun is built for landlords and property managers operating across the United States and Canada, so you can manage a mixed portfolio without switching tools or worrying about cross-border blind spots. Features like tenant screening, online payments, and lease management work in both countries."
    },
    {
      "q": "What is the best property maintenance software for small landlords?",
      "a": "Small landlords need something lightweight enough to get started quickly but capable enough to grow with them. Revun is free for up to 2 units, so independent landlords can run maintenance tracking, tenant messaging, and rent collection without paying anything upfront. As a portfolio grows beyond that, the per-door pricing stays affordable compared to enterprise platforms that lock core features behind higher tiers."
    },
    {
      "q": "Can I switch to new property maintenance software without losing my data?",
      "a": "Switching platforms is a common concern, but most modern property management tools including Revun allow you to import existing tenant records, lease dates, and maintenance history so you are not starting from zero. The key is making sure your current software can export a clean CSV or file format that the new platform accepts. Revun's onboarding process is designed to get landlords operational quickly rather than leaving them to figure out migration on their own."
    },
    {
      "q": "Does property maintenance management software integrate with accounting tools like QuickBooks?",
      "a": "Integration depth varies by platform: some tools offer a native QuickBooks sync, while others export reports you can reconcile manually. Revun includes built-in accounting so income, expenses, and maintenance costs are tracked inside the same system without requiring a separate bookkeeping tool. For landlords who still prefer QuickBooks or another external tool, having clean categorized data in one place makes that export straightforward."
    }
  ],
  "tenant-portal-software": [
    {
      "q": "What does tenant portal software actually do?",
      "a": "Tenant portal software gives renters a dedicated online space to pay rent, submit maintenance requests, view lease documents, and communicate with their property manager without playing phone tag. For landlords and managers, it centralizes everything from screening and leasing through ongoing communications and accounting in one place. Revun bundles all of these workstreams into a single platform so neither side needs separate apps for different tasks."
    },
    {
      "q": "How much does tenant portal software cost for small landlords?",
      "a": "Pricing varies widely across products, ranging from free tiers with limited features to per-unit monthly fees that stack up fast as your portfolio grows. Revun uses flat per-door pricing with a free plan for landlords managing one or two units, making it accessible without a long-term contract to test whether it fits your workflow. Larger portfolios stay on a predictable per-door rate rather than paying separately for add-on modules."
    },
    {
      "q": "Does tenant portal software work in Canada as well as the United States?",
      "a": "Many platforms are built primarily around US payment rails, lease law defaults, and tax reporting, which can create friction for Canadian landlords. Revun is built for both the US and Canada, supporting local payment methods, cross-border owner accounting, and multi-currency rent collection so portfolios spanning both countries run through the same dashboard."
    },
    {
      "q": "Can I switch to new tenant portal software without losing my existing lease and payment history?",
      "a": "Switching property management software is a real concern because tenant ledgers, lease dates, maintenance history, and security deposit records all need to carry over accurately. Most modern platforms including Revun offer a structured onboarding process with data import support, so your existing records migrate before you go live with tenants. Reaching out to the support team before signing up to map out your specific data is the best first step."
    },
    {
      "q": "What integrations does tenant portal software typically support?",
      "a": "Common integration needs include accounting exports to QuickBooks or Xero, listing syndication to Zillow or Apartments.com, background and credit screening services, and e-signature tools for leases. Revun has screening, e-leasing, payments, maintenance, and accounting built natively so fewer third-party connections are required in the first place. Where external tools are needed, standard exports and API access cover most workflows."
    },
    {
      "q": "Is tenant portal software worth it if I only manage a few rental units?",
      "a": "For landlords with just one or two properties, the main question is whether the time saved on rent collection, maintenance tracking, and tenant communication justifies the cost. Since Revun is free for up to two units with full portal functionality, small landlords can use a professional-grade system without paying anything until their portfolio grows. Even at a small scale, having a single organized record of payments and requests reduces disputes and saves hours at tax time."
    }
  ],
  "real-estate-communications-software": [
    {
      "q": "What does real estate communications software actually do?",
      "a": "Real estate communications software centralizes every touchpoint between property managers, landlords, tenants, and vendors into one place, covering things like automated lease notices, maintenance request updates, payment reminders, and tenant announcements. Instead of juggling email threads, spreadsheets, and phone calls, everything is logged and searchable. Revun bundles communications alongside leasing, payments, maintenance, screening, and accounting so your team works from a single platform rather than stitching together five separate tools."
    },
    {
      "q": "How much does real estate communications software cost?",
      "a": "Most platforms charge a flat per-door monthly fee, typically ranging from a few dollars to over ten dollars per unit depending on the feature set. Some tools also layer on onboarding fees or charge extra for add-ons like e-signatures or tenant screening. Revun uses straightforward per-door pricing with no hidden charges, and it is completely free for portfolios of one or two units."
    },
    {
      "q": "Does real estate communications software work for both US and Canadian landlords?",
      "a": "Not all platforms support both markets, since lease law, payment rails, and provincial or state disclosure requirements differ significantly between the US and Canada. You will want to confirm the tool handles ACH and EFT payments, supports bilingual notices if needed, and keeps up with local regulatory changes on both sides of the border. Revun is built for North American landlords and property managers, covering both US and Canadian portfolios under one account."
    },
    {
      "q": "Who is real estate communications software designed for, small landlords or large property managers?",
      "a": "It depends on the platform. Some are built exclusively for enterprise portfolios with hundreds of doors, while others scale from a single unit up to large multi-family operations. The best options serve both, with pricing that makes sense for a two-unit landlord and features robust enough for a professional property management firm. Revun is designed to work at every scale, starting free for one to two units and scaling with flat per-door pricing as your portfolio grows."
    },
    {
      "q": "Can real estate communications software replace my current property management tools?",
      "a": "If your current setup involves a separate leasing tool, a payment processor, a maintenance ticketing system, and a communication app, a true all-in-one platform can consolidate all of that into one workflow. The key is confirming the replacement actually covers every function you rely on today, including accounting and tenant screening, not just messaging. Revun includes leasing, online payments, maintenance tracking, communications, screening, and accounting in a single platform, so most landlords can retire multiple subscriptions when they switch."
    },
    {
      "q": "How hard is it to switch to a new real estate communications software platform?",
      "a": "Switching is usually easier than it looks once you identify a platform with solid onboarding support and straightforward data import for your existing tenant and lease records. The bigger risk is choosing a tool that only solves part of the problem and forces you to keep legacy systems running alongside it. Revun is designed to bring everything under one roof, which means the migration effort pays off faster because you are not maintaining two separate workflows after you move."
    }
  ],
  "owner-portal": [
    {
      "q": "What does property owner portal software actually do?",
      "a": "Property owner portal software gives landlords and investors a centralized dashboard to track rent payments, maintenance requests, lease status, and financial reports across their entire portfolio. Instead of juggling spreadsheets, email threads, and separate apps, everything lives in one place. Revun bundles leasing, payments, maintenance, tenant screening, communications, and accounting into a single portal so owners always have a live view of their properties."
    },
    {
      "q": "How much does property owner portal software cost?",
      "a": "Most platforms charge a flat monthly fee per door, typically ranging from $1 to $3 per unit depending on the feature tier. Revun uses transparent flat per-door pricing with no hidden transaction fees, and owners with one or two units can get started for free. That makes it practical whether you manage a single rental or a large portfolio."
    },
    {
      "q": "Does property management portal software work in Canada as well as the US?",
      "a": "Not all platforms are built for cross-border portfolios since Canadian banking, tax reporting, and tenancy rules differ by province. Revun is designed for landlords and operators across both the US and Canada, handling payments and compliance requirements in either country. If you own properties in multiple markets, look for a platform that explicitly supports both rather than assuming US-only tools will adapt."
    },
    {
      "q": "Can I switch from my current property management software without losing data?",
      "a": "Switching platforms is manageable when the new provider supports data import for leases, tenant records, and payment history. Revun offers an onboarding process that helps migrate existing portfolio data so you are not starting from scratch. It is worth confirming export formats with your current tool before you begin, since most platforms let you pull a CSV of tenants, units, and ledger entries."
    },
    {
      "q": "What integrations should I look for in owner portal software?",
      "a": "The most useful integrations connect your portal to ACH and credit card payment processors, accounting tools like QuickBooks, tenant screening services, and maintenance vendor workflows. Revun has these built in natively rather than requiring third-party add-ons, which reduces the number of subscriptions and sync errors you have to manage. If you already use a specific accounting package, confirm whether the platform syncs automatically or only exports reports."
    },
    {
      "q": "Is property owner portal software worth it if I only have a few rental units?",
      "a": "Even small landlords benefit from organized lease tracking, automated rent reminders, and a paper trail for maintenance and communications, especially at tax time. The math changes when a platform charges per door on a small portfolio, but Revun is free for one or two units so there is no cost barrier to getting organized early. Starting with good software habits also makes scaling to more doors much simpler down the road."
    }
  ],
  "accounting": [
    {
      "q": "What does property management accounting software actually do?",
      "a": "Property management accounting software handles rent collection, expense tracking, owner disbursements, and financial reporting in one place so you are not manually reconciling spreadsheets at month end. Revun builds all of this into the same platform your team already uses for leasing, maintenance, and tenant communication, so every dollar in and out is tied to a real unit, lease, or work order."
    },
    {
      "q": "How much does property management accounting software typically cost?",
      "a": "Most platforms charge per unit per month, and pricing ranges from around $1 to $3 per door depending on the feature tier. Revun uses flat per-door pricing with no hidden add-ons for accounting features, and properties with one or two units can use the platform free of charge."
    },
    {
      "q": "Does property management accounting software work for landlords in Canada as well as the US?",
      "a": "Many platforms are built only for US markets and do not handle Canadian banking, currency, or tax reporting properly. Revun is designed for landlords and property managers across the US and Canada, so it supports both markets without requiring workarounds or third-party plugins."
    },
    {
      "q": "Can I switch accounting software without losing my historical transaction data?",
      "a": "Switching is one of the most common concerns, and the short answer is yes, you can migrate with the right preparation: export your existing rent roll, open balances, and transaction history before importing into a new system. Revun has an onboarding process that walks you through data migration so your ledger history carries over and you are not starting from a blank slate."
    },
    {
      "q": "Does property management accounting software integrate with QuickBooks or other bookkeeping tools?",
      "a": "Some landlords prefer to keep a separate bookkeeping tool for tax filings or external accountant access, and many platforms offer QuickBooks sync for that reason. Revun includes native accounting built directly into the platform, which eliminates the need for a separate sync in most cases, though you can always export clean reports in standard formats for your accountant."
    },
    {
      "q": "Is property management accounting software worth it if I only have a few rental units?",
      "a": "For landlords with just a few doors, the main value is time saved on rent tracking, late fee calculations, and owner statements rather than raw cost savings. Revun is free for one to two units, so smaller landlords can use the full accounting feature set without paying anything until their portfolio grows."
    }
  ]
}
