import type { Competitor } from './competitors'

/* AUTO-GENERATED by the revun-compare-expansion workflow (2026-06-04). Do not hand-edit. */

export const generatedCompetitors: Record<string, Competitor> = {
  "rent-manager": {
    "slug": "rent-manager",
    "name": "Rent Manager",
    "letter": "R",
    "category": "Enterprise PM software",
    "tagline": "Revun vs Rent Manager",
    "heroSub": "Comparing all-in-one simplicity and flat pricing against Rent Manager's deep customization",
    "intro": "Rent Manager is a long-standing property management platform built for operators running mid-to-large portfolios across residential, commercial, manufactured housing, student housing, and short-term-stay properties. It earns its reputation on deep accounting, highly configurable workflows, and the ability to handle complex multi-entity ownership structures. The platform is primarily positioned for US-based operators and its Canadian support is limited to general North American availability rather than Canada-specific compliance or features. Teams that need maximum configurability and can absorb a steeper learning curve tend to find it a strong fit, while smaller or growth-stage operators often find its complexity and add-on cost structure a friction point.",
    "theirStrengths": [
      "Deep accounting and financial reporting built for complex multi-entity portfolios, with robust bank reconciliation, budgeting, and tax tooling that enterprise operators rely on.",
      "Highly configurable platform with custom fields, custom reports, configurable dashboards, and workflow automation that power users can shape to almost any operational model.",
      "Proven track record serving a wide range of asset classes including residential, commercial, manufactured housing, RV parks, self-storage, and affordable housing, giving operators flexibility as their portfolio mix evolves."
    ],
    "whereRevunWins": [
      {
        "title": "Native communications stack included at no extra cost",
        "body": "Rent Manager's VoIP product (rmVoIP) is a paid add-on that third-party reviews describe as basic telephony. Revun ships email, SMS, VoIP, and video natively in every plan with no separate module fee, so your team communicates from one inbox without juggling vendors or surprise line items."
      },
      {
        "title": "Flat per-door pricing with no unit minimums and a free tier",
        "body": "Rent Manager published pricing starts around $1 per unit per month but carries a minimum threshold before you can get started, and there is no free version. Revun charges a flat per-door rate with no portfolio-size floor and offers a free plan for owners managing one or two units, making it accessible from day one whether you have 2 doors or 2,000."
      },
      {
        "title": "Built for US and Canada from the ground up",
        "body": "Rent Manager is primarily a US-focused product with no documented Canadian-specific compliance or lease frameworks. Revun is architected for both markets, covering province-level and state-level requirements, so property managers operating across the border do not need a second platform or manual workarounds."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "partial",
        "note": "Primarily US-focused; Canadian operators can use the software but no Canada-specific compliance or lease frameworks are documented."
      },
      {
        "key": "allinone",
        "competitor": "partial",
        "note": "Core accounting and leasing are bundled, but communications (VoIP) and some screening functions are separate paid add-ons or third-party integrations."
      },
      {
        "key": "comms",
        "competitor": "partial",
        "note": "rmVoIP is available as a paid add-on; SMS and email notifications exist but native video is absent and the communications layer is not unified in one inbox."
      },
      {
        "key": "screening",
        "competitor": "partial",
        "note": "Tenant screening is available via third-party integrations within the leasing workflow rather than a fully built-in screening engine."
      },
      {
        "key": "ai",
        "competitor": "partial",
        "note": "AI assists with accounts receivable and payable workflows and a writing assistant for marketing copy, but broad AI automation across operations is limited."
      },
      {
        "key": "pricing",
        "competitor": "partial",
        "note": "Per-unit pricing published starting around $1 per unit per month, but a minimum portfolio threshold applies and implementation fees are additional."
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "Full-featured accounting suite is a core differentiator: automated rent collection, AP and AR, bank reconciliation, budgeting, and multi-entity reporting."
      },
      {
        "key": "freetier",
        "competitor": "no",
        "note": "No free version and no free trial offered; the platform requires a paid subscription to access any functionality."
      }
    ],
    "pricingNote": "Rent Manager's published pricing starts around $1 per unit per month on the Basic tier, with higher tiers at approximately $1.50 and $2.25 per unit per month. Exact costs vary based on portfolio size, selected modules, and implementation or training fees that are billed separately. Verify current pricing directly with Rent Manager before budgeting.",
    "bestForThem": "Rent Manager is a strong fit for established property management companies in the US running 200 or more units across mixed asset classes who need deep accounting customization, multi-entity financial reporting, and are comfortable building out a tech stack with multiple add-on modules.",
    "bestForRevun": "Revun is the better choice for operators who want a single platform covering US and Canadian properties, need communications (email, SMS, VoIP, video) and tenant screening without paying for separate modules, and prefer transparent flat per-door pricing that scales from a first rental unit up to an institutional portfolio.",
    "migration": "Revun's onboarding team imports your existing tenant records, lease data, and payment history from Rent Manager exports in CSV or standard formats. Most migrations complete within two to four weeks depending on portfolio size. Your accounting history, open work orders, and contact records transfer with no re-entry required, and your team gets a dedicated migration specialist throughout the process.",
    "faqs": [
      {
        "q": "Is Revun a good Rent Manager alternative?",
        "a": "Yes, particularly for operators who find Rent Manager's module-based pricing and learning curve difficult to justify. Revun includes communications, screening, accounting, and AI automation in one flat per-door plan and is built to serve both US and Canadian portfolios, which Rent Manager does not natively support."
      },
      {
        "q": "Does Rent Manager work in Canada?",
        "a": "Rent Manager operates across North America and Canadian property managers can use the platform, but it does not offer Canada-specific lease frameworks, province-level compliance tools, or localized payment rails. Revun is built for both markets from the ground up, covering US and Canadian regulatory requirements in a single platform."
      },
      {
        "q": "Can I migrate from Rent Manager to Revun?",
        "a": "Yes. Revun supports data migration from Rent Manager using standard CSV exports. Tenant records, lease terms, payment history, and contact data all transfer, and Revun's migration team assigns a dedicated specialist to guide your portfolio through the transition, typically completing within two to four weeks."
      },
      {
        "q": "How does Revun pricing compare to Rent Manager?",
        "a": "Rent Manager published pricing starts around $1 per unit per month on the Basic plan, with a minimum portfolio threshold required before you can subscribe, plus separate fees for implementation, training, and add-on modules like VoIP. Revun charges a single flat per-door rate with no unit minimum, no add-on fees for communications or screening, and a free plan for portfolios of one to two units."
      }
    ]
  },
  "realpage": {
    "slug": "realpage",
    "name": "RealPage",
    "letter": "R",
    "category": "Enterprise PM software",
    "tagline": "The enterprise incumbent built for large multifamily portfolios",
    "heroSub": "Comparing Revun vs RealPage for property managers who want all-in-one software without enterprise lock-in",
    "intro": "RealPage is a Texas-based property management platform that has spent two decades consolidating the enterprise end of the US rental market, claiming more than 24 million units under management. Its core strength is deep multifamily operations tooling, revenue management, and a large analytics data set. The platform is built around large portfolio operators and institutional landlords, and its pricing, implementation process, and add-on module structure reflect that focus. Independent landlords, smaller operators, and Canadian property managers routinely find that RealPage either does not fit their scale or requires substantial professional-services investment before delivering value.",
    "theirStrengths": [
      "Massive rental data network with over 30 million lease outcome records powering its AI screening and revenue management models, giving large portfolio operators benchmarking depth no startup can match today.",
      "Purpose-built multifamily accounting and asset management suite that handles complex institutional reporting, investor distributions, and GAAP-compliant financials at scale across thousands of units.",
      "Broad partner and integration ecosystem through its RealPartners program, meaning large operators can connect RealPage to existing ERP, revenue management, and business intelligence tools they already run."
    ],
    "whereRevunWins": [
      {
        "title": "Flat per-door pricing with no unit minimums",
        "body": "RealPage does not publish pricing and requires a custom quote; analysts estimate meaningful per-user or per-unit costs that scale unfavorably for portfolios under a few hundred doors. Revun charges a flat rate per door with no minimum commitment and a free tier for 1 to 2 units, so a 15-door landlord pays the same proportional rate as a 500-door operator."
      },
      {
        "title": "US and Canada native compliance out of the box",
        "body": "RealPage is architected around US multifamily regulations. Canadian operators report that provincial tenancy rules, CAD currency handling, and local compliance requirements require workarounds or are simply unsupported. Revun is built for both markets from day one, with no need for a partner or custom configuration to operate legally in Canadian provinces."
      },
      {
        "title": "Native communications stack with no add-ons required",
        "body": "RealPage's core product handles maintenance requests and rent payments but routes voice answering and outbound calling to third-party integrations or separate modules. Revun includes email, SMS, VoIP, and video natively in every plan, so property managers run all resident communication from one inbox without paying for a bolt-on telephony layer."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "partial",
        "note": "US coverage is deep; Canadian compliance support is limited and typically requires partner configuration"
      },
      {
        "key": "allinone",
        "competitor": "partial",
        "note": "Core platform is broad but communications, revenue management, and some screening tiers are sold as separate add-on modules"
      },
      {
        "key": "comms",
        "competitor": "partial",
        "note": "Resident portal handles messages and maintenance; native VoIP and outbound calling are not part of the standard stack"
      },
      {
        "key": "screening",
        "competitor": "yes",
        "note": "AI Screening is a genuine differentiator, backed by 30M+ lease records and a predictive scoring model"
      },
      {
        "key": "ai",
        "competitor": "partial",
        "note": "AI powers screening and YieldStar revenue management well; AI for routine communications and leasing workflows is narrower and tied to specific modules"
      },
      {
        "key": "pricing",
        "competitor": "no",
        "note": "No public per-unit pricing; custom enterprise quotes with implementation fees make cost opaque for smaller portfolios"
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "Full GAAP-compliant accounting suite with investor reporting is one of RealPage's strongest capabilities"
      },
      {
        "key": "freetier",
        "competitor": "no",
        "note": "No free tier; onboarding typically requires a paid implementation engagement regardless of portfolio size"
      }
    ],
    "pricingNote": "RealPage does not publish standard pricing. Published analyst estimates and third-party review sites suggest entry-level costs starting around $35 per user per month for basic tiers, with enterprise contracts running substantially higher and often including implementation and professional-services fees on top of subscription costs. Always request a formal quote directly from RealPage for accurate current figures.",
    "bestForThem": "RealPage fits best for institutional owners and large multifamily operators in the US running 500 or more units who need deep revenue management, GAAP investor reporting, and are willing to invest in implementation and ongoing professional services to get there.",
    "bestForRevun": "Revun is the stronger fit for independent landlords, regional property managers, and growing operators across the US and Canada who want a single platform covering communications, screening, accounting, and AI automation at a predictable flat per-door price with no minimum unit count.",
    "migration": "RealPage stores lease data, resident history, maintenance records, and accounting transactions in its own data model. Revun's onboarding team can ingest exported CSV or Excel files for tenant rosters, open balances, and lease terms. For accounting history, a clean cutover at a month-end or fiscal year boundary is the lowest-risk approach. Most operators are fully operational in Revun within two to four weeks without needing a third-party migration consultant.",
    "faqs": [
      {
        "q": "Is Revun a good RealPage alternative?",
        "a": "For most independent landlords and regional operators, yes. Revun covers the same core functions (leasing, tenant screening, accounting, resident communications, and AI automation) at a flat per-door price with no unit minimums and no add-on modules required. RealPage is purpose-built for large institutional portfolios and its pricing and implementation process reflect that. If you manage fewer than a few hundred doors or operate in Canada, Revun is likely the more practical and cost-effective choice."
      },
      {
        "q": "Does RealPage work in Canada?",
        "a": "RealPage is designed around US multifamily regulations and does not natively support Canadian provincial tenancy rules, CAD currency, or Canadian compliance requirements. Some operators use RealPage in Canada through implementation partners who build workarounds, but out-of-the-box Canadian support is limited. Revun is built for both the US and Canada from the ground up, with no additional configuration needed for Canadian operators."
      },
      {
        "q": "Can I migrate from RealPage to Revun?",
        "a": "Yes. RealPage allows data exports of tenant records, lease terms, open balances, and transaction history. Revun's onboarding team guides you through importing those files so your portfolio is live without manual re-entry. The cleanest migration timing is at a month-end or fiscal year boundary. Most operators complete the transition in two to four weeks."
      },
      {
        "q": "How does Revun pricing compare to RealPage?",
        "a": "RealPage does not publish standard pricing and requires a custom enterprise quote; third-party review sites cite entry-level estimates starting around $35 per user per month before implementation fees. Revun charges a flat fee per door with no unit minimums and offers a free tier for portfolios of one to two units. For most portfolios under a few hundred doors the total cost of ownership on Revun is meaningfully lower, with no add-on modules needed for communications, screening, or accounting."
      }
    ]
  },
  "entrata": {
    "slug": "entrata",
    "name": "Entrata",
    "letter": "E",
    "category": "Multifamily PM software",
    "tagline": "The OS for Autonomous Property Management",
    "heroSub": "Comparing Revun vs Entrata for US and Canadian property managers in 2026",
    "intro": "Entrata markets itself as an operating system for multifamily property management, unifying leasing, operations, resident engagement, and accounting into one platform. The company primarily targets mid-size to large multifamily operators, student housing communities, affordable housing portfolios, and commercial property managers. Entrata has expanded into Canada, though its footprint there remains limited compared to its deep US presence. It is a strong fit for established enterprise operators who want a single vendor with a wide module catalog and dedicated account management, but its pricing model and implementation complexity can make it a heavy lift for smaller or growing portfolios.",
    "theirStrengths": [
      "Purpose-built multifamily depth: Entrata's module library covers leasing CRM, reputation management, utility billing, procurement, and revenue intelligence in a single platform purpose-built for large apartment communities.",
      "Dedicated account management and enterprise support: Users consistently praise Entrata's assigned account representatives and responsive support teams, which matter when managing thousands of units across multiple properties.",
      "AI-powered automation at scale (ELI+): Entrata's ELI+ layer automates leasing follow-ups, tour scheduling, payment nudges, and renewal workflows, giving large operators meaningful efficiency gains across high-volume portfolios."
    ],
    "whereRevunWins": [
      {
        "title": "Flat per-door pricing with no unit minimums",
        "body": "Entrata negotiates custom contracts with per-unit fees plus base fees and add-on module charges, and a 1,500-unit portfolio can exceed $45,000 per year. Revun charges a single flat per-door rate with no unit minimums and a free tier for 1 to 2 units, so owners scale up without surprise line items or sales negotiations."
      },
      {
        "title": "Native communications stack included",
        "body": "Entrata provides a resident portal and mass messaging, but native VoIP calling and video are not part of the core platform. Revun bundles email, SMS, VoIP, and video in every plan, so property managers run every conversation from one inbox without stitching together third-party calling tools."
      },
      {
        "title": "True US and Canada compliance from day one",
        "body": "Entrata announced Canadian expansion in 2022 with an initial Toronto focus, but the platform was built US-first and Canadian coverage outside major metros remains limited. Revun is engineered for both US and Canadian regulatory environments from launch, covering lease law, payment rails, and screening requirements across both countries."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "partial",
        "note": "US-native with a 2022 Canadian expansion starting in Toronto; coverage outside major Canadian metros is still limited."
      },
      {
        "key": "allinone",
        "competitor": "partial",
        "note": "Core modules are unified, but several features (reputation management, utility billing, procurement) are add-on products that raise total cost."
      },
      {
        "key": "comms",
        "competitor": "partial",
        "note": "Resident portal and mass messaging are included; native VoIP and video calling are not part of the standard platform."
      },
      {
        "key": "screening",
        "competitor": "partial",
        "note": "Tenant screening is available through integrations and add-on modules rather than fully bundled into the base subscription."
      },
      {
        "key": "ai",
        "competitor": "yes",
        "note": "ELI+ provides purpose-built AI agents for leasing, payments, renewals, and maintenance automation across the resident lifecycle."
      },
      {
        "key": "pricing",
        "competitor": "no",
        "note": "Custom quote-based contracts with base fees plus per-unit charges plus module add-ons; no self-serve pricing and contracts typically target portfolios of meaningful scale."
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "Full accounting, budgeting, and financial reporting are built into the platform as core functionality."
      },
      {
        "key": "freetier",
        "competitor": "no",
        "note": "No free tier is offered; Entrata requires a sales engagement and custom contract for all customers regardless of portfolio size."
      }
    ],
    "pricingNote": "Entrata does not publish pricing publicly. Based on available market data, published pricing starts around $1 per unit per month for smaller accounts, and total annual costs for a 1,500-unit portfolio can run well above $40,000 once base fees and module add-ons are factored in. Contact Entrata sales for a current quote specific to your portfolio size and feature needs.",
    "bestForThem": "Entrata is a strong choice for established multifamily operators managing 200 or more units in the US who want a deep module catalog, dedicated account support, and enterprise-grade AI automation, and who have the implementation resources and budget to match.",
    "bestForRevun": "Revun is the better fit for independent landlords, growing property managers, and US or Canadian operators at any portfolio size who want flat predictable pricing, a fully native communications stack, and built-in screening and accounting without negotiating custom contracts or paying for add-on modules.",
    "migration": "Entrata exports resident ledgers, lease documents, and work order history in standard formats. A Revun onboarding specialist will map your Entrata data export to Revun's schema, import open balances and active leases, and configure your communication channels before go-live. Most portfolios complete the transition in two to four weeks.",
    "faqs": [
      {
        "q": "Is Revun a good Entrata alternative?",
        "a": "Yes, especially for property managers who find Entrata's custom contract model too expensive or complex for their portfolio size. Revun covers the same core workflows including leasing, tenant screening, communications, accounting, and AI automation at a flat per-door price with no unit minimums and a free tier for small portfolios."
      },
      {
        "q": "Does Entrata work in Canada?",
        "a": "Entrata announced a Canadian expansion in 2022 with an initial focus on the Toronto area. Coverage and compliance support outside major Canadian metros remains limited, and the platform was built primarily for US regulatory requirements. Revun is designed for both US and Canadian markets from the ground up."
      },
      {
        "q": "Can I migrate from Entrata to Revun?",
        "a": "Yes. Entrata allows data exports of resident records, lease agreements, ledger history, and maintenance logs. Revun's migration team will import your exported data, reconcile open balances, and set up your workflows so you can go live without manual re-entry."
      },
      {
        "q": "How does Revun pricing compare to Entrata?",
        "a": "Entrata uses a custom quote model with per-unit fees, base fees, and add-on module charges that are not published publicly. Available market data suggests annual costs can exceed $40,000 for larger portfolios. Revun charges a flat per-door rate with no unit minimums, no module surcharges, and a free plan for owners with 1 to 2 units."
      }
    ]
  },
  "resman": {
    "slug": "resman",
    "name": "ResMan",
    "letter": "R",
    "category": "Multifamily PM software",
    "tagline": "Purpose-built multifamily and affordable housing platform with strong compliance depth",
    "heroSub": "Comparing Revun vs ResMan for multifamily property managers in the US and Canada",
    "intro": "ResMan is a cloud-based property management platform designed primarily for conventional multifamily and affordable housing operators in the United States. It bundles leasing, accounting, maintenance, compliance, and resident services into tiered packages aimed at small portfolios through enterprise operators. The platform has earned a strong reputation among US-based teams managing HUD, Tax Credit, and Rural Development properties where regulatory compliance is a first-order concern. Managers who run purely US multifamily books and need deep affordable housing compliance tooling will find ResMan a capable incumbent, while those who operate across the US-Canada border or want flat, transparent pricing with no sales-call requirement will likely hit friction points quickly.",
    "theirStrengths": [
      "Affordable housing compliance depth: ResMan is one of the few platforms with dedicated HUD, Rural Development, and Tax Credit compliance workflows baked directly into the core product, making it a defensible choice for regulated US portfolios.",
      "Reporting and financial visibility: Users consistently cite ResMan's financial reporting suite as detailed and actionable, with property-level to portfolio-level dashboards that surface KPIs without requiring custom exports.",
      "Customer support quality: ResMan's support team receives strong marks for responsiveness and willingness to help operators customize the platform, which partially offsets the steeper onboarding curve on complex deployments."
    ],
    "whereRevunWins": [
      {
        "title": "US and Canada in one platform",
        "body": "Revun is built for North American operators from day one. Canadian lease structures, provincial tenancy rules, and CAD accounting work natively without workarounds. ResMan is US-centric and its Canadian support is limited, meaning cross-border portfolios end up patching gaps manually or running two systems."
      },
      {
        "title": "Flat per-door pricing with no unit minimums",
        "body": "Revun charges a single flat rate per door with no portfolio-size floor and a free tier for owners of one or two units. ResMan requires a demo call to get a quote, uses tiered packages with custom pricing, and publishes no self-serve starting price, which means smaller operators and growing portfolios absorb negotiation friction and unpredictable cost curves."
      },
      {
        "title": "Native communications and AI included by default",
        "body": "Revun ships email, SMS, VoIP, and video messaging in the core product alongside AI automation for leasing workflows, not as paid add-ons. ResMan offers email and text outreach but treats advanced marketing automation, chatbot functionality, and AI leasing tools as separate packages, so the all-in cost climbs quickly for teams that want those capabilities."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "partial",
        "note": "US multifamily and affordable housing covered well; Canadian market support is limited and not a documented focus."
      },
      {
        "key": "allinone",
        "competitor": "partial",
        "note": "Core accounting, leasing, and maintenance are bundled, but marketing automation, chatbot, utilities, and AP automation are paid add-ons."
      },
      {
        "key": "comms",
        "competitor": "partial",
        "note": "Email and SMS lead communication are included; VoIP and video are not native to the platform."
      },
      {
        "key": "screening",
        "competitor": "yes",
        "note": "Tenant screening with background and credit checks is integrated into the leasing workflow."
      },
      {
        "key": "ai",
        "competitor": "partial",
        "note": "AI-powered leasing tools exist but are positioned as a premium marketing package add-on rather than a default feature."
      },
      {
        "key": "pricing",
        "competitor": "no",
        "note": "Custom quote-only pricing with no published per-unit rate; tiered packages and no self-serve onboarding for small portfolios."
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "Full property accounting with budgeting, fraud detection, and financial reporting is a core strength of the platform."
      },
      {
        "key": "freetier",
        "competitor": "no",
        "note": "No free tier; all plans require a sales conversation and contract."
      }
    ],
    "pricingNote": "ResMan does not publish per-unit pricing publicly. Industry estimates and third-party review sites suggest published pricing starts around $1 to $3 per unit per month for mid-size portfolios, with additional costs for marketing, AI leasing, utilities, and AP automation modules. Actual quotes depend on portfolio size, tier selection, and negotiated terms, so total cost of ownership can differ substantially from any estimate. Contact ResMan directly for current pricing.",
    "bestForThem": "US-focused operators managing conventional multifamily or affordable housing portfolios (HUD, Tax Credit, Rural Development) who prioritize compliance depth, detailed financial reporting, and are comfortable with a sales-led buying process and modular add-on pricing.",
    "bestForRevun": "Property managers running portfolios across the US and Canada, independent landlords starting with one or two units, and operators who want AI automation, native communications (email, SMS, VoIP, video), tenant screening, and accounting all in one flat-rate product without a sales call or unit minimum.",
    "migration": "Migrating from ResMan to Revun typically involves exporting your rent rolls, lease abstracts, tenant contact records, and historical accounting data from ResMan's reporting suite. Revun's onboarding team accepts standard CSV and Excel exports for tenant and unit data, and can map ResMan's chart-of-accounts structure to Revun's accounting module. Most teams complete data migration within two to four weeks depending on portfolio size. Lease documents stored in ResMan should be downloaded before cancellation since access ends at contract termination.",
    "faqs": [
      {
        "q": "Is Revun a good ResMan alternative?",
        "a": "Yes, particularly for operators who want transparent flat per-door pricing, built-in communications (email, SMS, VoIP, and video), and a platform that covers both US and Canadian portfolios without add-ons. ResMan is stronger on US affordable housing compliance; Revun is stronger on all-in-one value, North American coverage, and self-serve onboarding."
      },
      {
        "q": "Does ResMan work in Canada?",
        "a": "ResMan is primarily designed for the US multifamily and affordable housing market. While it is technically available in Canada, its compliance workflows, lease structures, and support documentation are built around US regulations. Canadian operators typically encounter gaps around provincial tenancy rules and CAD accounting that require manual workarounds. Revun is built for US and Canada natively."
      },
      {
        "q": "Can I migrate from ResMan to Revun?",
        "a": "Yes. You can export tenant records, lease data, and financial history from ResMan as CSV or Excel files and import them into Revun during onboarding. Revun's team guides you through mapping your existing chart of accounts and unit data. Most portfolios complete the transition in two to four weeks. Download all stored lease documents from ResMan before your contract ends."
      },
      {
        "q": "How does ResMan pricing compare to Revun pricing?",
        "a": "ResMan does not publish its pricing publicly. Third-party estimates suggest costs in the range of $1 to $3 per unit per month for mid-size portfolios, with additional fees for marketing automation, AI leasing, utilities management, and AP automation modules. Revun uses flat per-door pricing with no unit minimums and a free tier for one to two units, so the total cost is visible before you ever speak to sales."
      }
    ]
  },
  "baselane": {
    "slug": "baselane",
    "name": "Baselane",
    "letter": "B",
    "category": "Landlord banking + software",
    "tagline": "Revun vs Baselane",
    "heroSub": "How does Baselane compare to Revun for landlords who need more than banking?",
    "intro": "Baselane is a US only landlord banking and financial management platform built around FDIC insured property specific checking accounts, automated rent collection, and AI assisted bookkeeping. It targets independent landlords and real estate investors who want a free or low cost way to separate property finances without switching to a full property management platform. The core tier is free and the platform earns strong marks for its accounting and banking layer. However Baselane is built banking first and property management second, which means landlords who need communications, maintenance, Canadian properties, or true all in one operations will hit its ceiling quickly.",
    "theirStrengths": [
      "Purpose built landlord banking with unlimited property specific FDIC insured accounts, high yield savings, and 1 to 5 percent cash back rewards that no general PM platform matches.",
      "Free core tier with no per unit fees and no minimum balance covers banking, rent collection, bookkeeping, and TransUnion tenant screening out of pocket costs passed to applicants, making it genuinely low cost for small US portfolios.",
      "Strong automated accounting layer with AI transaction tagging by property and tax category, Schedule E style reporting, and real time cash flow dashboards that solo landlords would otherwise pay a bookkeeper to produce."
    ],
    "whereRevunWins": [
      {
        "title": "US and Canada in one platform",
        "body": "Baselane is available only to US residents and uses a US chartered bank backbone, so Canadian landlords or cross border portfolios are simply locked out. Revun is built for both markets from day one, with compliance, currency handling, and local regulatory context on both sides of the border."
      },
      {
        "title": "Native communications built in",
        "body": "Baselane provides a basic tenant portal for rent payments but has no native messaging, email, SMS, VoIP, or video. Landlords must bolt on a separate tool for every tenant conversation. Revun includes email, SMS, VoIP, and video in a single inbox so every interaction and its audit trail lives in the same platform as the lease and the ledger."
      },
      {
        "title": "AI automation across operations, not just tagging",
        "body": "Baselane applies AI to transaction categorization. Revun extends AI automation to the full operations layer including lease drafting, maintenance triage, tenant communication drafts, and renewal workflows. That difference compounds across a growing portfolio where manual touchpoints are the real cost."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "no",
        "note": "US only. Baselane banking requires a US address and Social Security Number. Canadian landlords cannot open an account."
      },
      {
        "key": "allinone",
        "competitor": "partial",
        "note": "Banking and accounting are strong but no maintenance requests, no listing syndication, no native communications, and no AI workflow automation."
      },
      {
        "key": "comms",
        "competitor": "no",
        "note": "No native email, SMS, VoIP, or video. The tenant portal handles payment notifications only."
      },
      {
        "key": "screening",
        "competitor": "partial",
        "note": "TransUnion SmartMove screening is available per report with cost passed to the applicant, but it is an add on flow rather than a native integrated step in the leasing pipeline."
      },
      {
        "key": "ai",
        "competitor": "partial",
        "note": "AI is used for transaction tagging and tax category assignment. No AI workflow automation for leasing, communications, or maintenance."
      },
      {
        "key": "pricing",
        "competitor": "yes",
        "note": "No per unit fees and no minimums. Core tier is free. Published pricing for the Smart upgrade starts around $20 per month billed annually."
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "This is Baselane's flagship strength. Property specific accounts, Schedule E reporting, cash flow dashboards, and AI categorization are genuinely robust."
      },
      {
        "key": "freetier",
        "competitor": "yes",
        "note": "Free tier covers banking, rent collection, bookkeeping, and screening access with no unit cap and no time limit."
      }
    ],
    "pricingNote": "Baselane's published pricing starts around $0 per month for the core banking and bookkeeping tier, with a premium upgrade reported around $20 per month billed annually for features like faster rent disbursement. Individual tenant screening reports carry a per report fee typically passed to the applicant. Pricing details can change so confirm current rates on Baselane's website before making a decision.",
    "bestForThem": "Independent US based landlords with one to twenty or so units who want a free financial layer (banking plus bookkeeping plus basic rent collection) and are comfortable using separate tools for communications, maintenance, and leasing.",
    "bestForRevun": "Landlords and property managers who operate in both the US and Canada, want a single platform for operations and finances, need native tenant communications without third party bolt ons, or are scaling to the point where manual coordination across multiple tools is the real bottleneck.",
    "migration": "Migrating from Baselane to Revun is straightforward because Baselane is not a system of record for leases or maintenance history. Export your transaction history and Schedule E reports as CSV or PDF from the Baselane dashboard, import open rent schedules and tenant contact records into Revun, and redirect future rent collection to your Revun account. Tenants receive a one time re enrollment notification. The banking transition is the only manual step: close or drain Baselane accounts after all in flight payments clear, typically within one billing cycle.",
    "faqs": [
      {
        "q": "Is Revun a good Baselane alternative?",
        "a": "Yes, particularly if you need more than banking. Baselane excels at property specific accounts and bookkeeping for US landlords, but it does not cover native communications, maintenance, AI workflow automation, or Canadian properties. Revun handles all of those in one platform while matching Baselane on free entry level access and no per unit minimums."
      },
      {
        "q": "Does Baselane work in Canada?",
        "a": "No. Baselane requires a US address and Social Security Number and is available only to residents of the 50 US states and DC. Canadian landlords and cross border portfolios cannot use Baselane. Revun is built for both the US and Canada from the ground up."
      },
      {
        "q": "Can I migrate from Baselane to Revun?",
        "a": "Yes, and it is relatively low friction. Export your transaction history and reports from Baselane, bring tenant and lease records into Revun, and redirect rent collection. Because Baselane does not store maintenance history or communications, there is no complex data migration. Most landlords complete the switch within a single billing cycle."
      },
      {
        "q": "How does Baselane pricing compare to Revun?",
        "a": "Baselane's core tier is free with no per unit fees, and a premium tier is published at around $20 per month billed annually. Revun uses flat per door pricing with no unit minimums and a free tier for one to two units. For small portfolios both start at zero cost. As portfolios scale, the right comparison is total platform cost including the third party tools Baselane requires for communications and operations that Revun includes natively."
      }
    ]
  },
  "stessa": {
    "slug": "stessa",
    "name": "Stessa",
    "letter": "S",
    "category": "Rental finance tracking",
    "tagline": "Built for investors who track. Built for landlords who manage everything.",
    "heroSub": "How Stessa compares to Revun for landlords who need more than a ledger",
    "intro": "Stessa is a US-focused rental finance and property tracking platform built for real estate investors, particularly those managing single-family rentals, small multifamily portfolios, and short-term rentals. It earns strong marks for automated bookkeeping, real-time financial dashboards, and a generous free tier that has made it popular with self-managing landlords. Where Stessa concentrates on the money side of landlord life, Revun is an all-in-one platform covering communications, tenant screening, accounting, and AI automation in a single subscription with flat per-door pricing that scales from one unit to thousands, across both the US and Canada.",
    "theirStrengths": [
      "Stessa's automated bookkeeping is genuinely excellent: it connects directly to bank and credit accounts, categorizes rental income and expenses with minimal manual input, and generates investor-grade reports including income statements, net cash flow summaries, and Schedule of Real Estate Owned exports that are ready for tax time.",
      "The free plan is one of the most capable in the market for small portfolios, giving independent landlords access to core financial tracking, rent collection, and basic tenant applications at no cost, making Stessa a low-friction entry point for new or part-time investors.",
      "Stessa's purpose-built banking product, which lets landlords open separate high-yield FDIC-insured accounts per property that feed directly into its bookkeeping engine, is a differentiated feature that tightens the loop between cash management and reporting in a way most property management platforms do not offer."
    ],
    "whereRevunWins": [
      {
        "title": "US and Canada in one platform",
        "body": "Stessa's core features, including its banking product and tenant screening powered by RentPrep and TransUnion, are built around US compliance, US financial rails, and US-specific lease templates. Canadian landlords can access the interface and use some features, but provincial tenancy law compliance, Canadian banking integrations, and Canada-specific screening are not built in. Revun is designed from the ground up for both markets, with compliance support, currency handling, and screening networks that work across all 50 states and all 10 provinces."
      },
      {
        "title": "Native communications built in, not bolted on",
        "body": "Stessa does not include a native communication layer. Landlords who need to contact tenants must switch to a separate email client, SMS app, or phone system, creating gaps in the paper trail and adding tool overhead. Revun bundles email, SMS, VoIP calling, and video into the same platform where leases, maintenance requests, and rent ledgers live. Every conversation is logged against the tenant record automatically."
      },
      {
        "title": "AI automation that runs the workflow, not just reports it",
        "body": "Stessa surfaces financial data well but does not apply AI to automate the property management workflow itself. Revun's AI layer handles tasks like late-payment nudges, maintenance triage, lease renewal prompts, and applicant follow-up without manual scheduling. For landlords who want their software to act, not just account, Revun's automation layer is a material upgrade over Stessa's reporting-first model."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "partial",
        "note": "US-built; Canadian landlords can use the interface but provincial compliance, Canadian banking rails, and CAD-native screening are not supported."
      },
      {
        "key": "allinone",
        "competitor": "partial",
        "note": "Strong on finance tracking and rent collection; lacks native communications, VoIP, and advanced maintenance management without third-party tools."
      },
      {
        "key": "comms",
        "competitor": "no",
        "note": "No built-in email, SMS, VoIP, or video. Landlords must handle tenant communication in separate apps."
      },
      {
        "key": "screening",
        "competitor": "partial",
        "note": "Tenant screening is available via RentPrep/TransUnion partnership; basic reports included but income verification and premium add-ons carry extra per-report fees."
      },
      {
        "key": "ai",
        "competitor": "partial",
        "note": "Some smart categorization and financial automation; no AI-driven workflow automation for communications, maintenance triage, or lease renewal."
      },
      {
        "key": "pricing",
        "competitor": "partial",
        "note": "Published pricing starts around $28 per month (annual) for the Pro plan; pricing is feature-gated rather than per-door, which suits small portfolios but adds friction at scale."
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "Stessa's core strength: automated bookkeeping, bank-feed categorization, investor-grade reports, and a property-linked banking product are all built in."
      },
      {
        "key": "freetier",
        "competitor": "yes",
        "note": "Free plan covers core financial tracking, online rent collection, and basic rental applications for unlimited properties."
      }
    ],
    "pricingNote": "Stessa's published pricing starts around $28 per month on an annual plan for the Pro tier, with a free plan available for landlords who need core bookkeeping and rent collection without advanced features. Pricing is structured by feature tier rather than per door, so costs do not scale linearly with portfolio size. Always verify current pricing at stessa.com before making a purchasing decision.",
    "bestForThem": "Stessa is a strong fit for US-based real estate investors who want sophisticated rental finance tracking and investor-grade reporting without paying for a full property management suite. It is especially well suited to passive investors with small to mid-size portfolios who already have a communication workflow and simply need their numbers organized for tax season and portfolio decisions.",
    "bestForRevun": "Revun is the better choice for landlords and property managers who need a single platform to handle communications, screening, leasing, maintenance, accounting, and AI-driven automation across US and Canadian properties, particularly those who are scaling beyond a handful of units and do not want to stitch together multiple tools to cover the full management lifecycle.",
    "migration": "Exporting your data from Stessa is straightforward: download your transaction history, income statements, and tenant ledgers as CSV files from the Reports section, and export any lease documents you have stored. Revun's onboarding team maps your transaction categories to Revun's chart of accounts during setup, imports your tenant and property records, and replicates your rent collection schedule so the first collection cycle runs without a gap. Most landlords complete the switch in under a week.",
    "faqs": [
      {
        "q": "Is Revun a good Stessa alternative?",
        "a": "Yes, particularly if you want more than finance tracking. Stessa excels at bookkeeping and investor reporting. Revun covers the same accounting ground and adds native email, SMS, VoIP, video, AI automation, and tenant screening in one flat-rate subscription, so you can manage the full landlord workflow without switching between apps."
      },
      {
        "q": "Does Stessa work in Canada?",
        "a": "Stessa's interface is accessible to Canadian users, but the platform is US-built. Its banking product, tenant screening network, and lease templates are designed for US landlords. Canadian-specific compliance, provincial tenancy law guidance, and CAD banking integrations are not natively supported. Revun is built for both the US and Canada from the ground up."
      },
      {
        "q": "Can I migrate from Stessa to Revun?",
        "a": "Yes. Stessa lets you export transaction history, reports, and documents as CSV and PDF files. Revun's onboarding process imports your property and tenant records, maps your historical categories, and carries over your rent collection setup. Most landlords complete the migration in under a week with no gap in rent collection."
      },
      {
        "q": "How does Revun pricing compare to Stessa?",
        "a": "Stessa's published pricing starts around $28 per month (billed annually) for the Pro plan, with a free tier for basic use. Revun uses flat per-door pricing with no unit minimums and a free tier for landlords with one or two units. As a portfolio grows, Revun's per-door model tends to offer more predictable scaling costs compared to a feature-gated tier that may require an upgrade regardless of portfolio size."
      }
    ]
  },
  "azibo": {
    "slug": "azibo",
    "name": "Azibo",
    "letter": "A",
    "category": "Landlord banking + software",
    "tagline": "Free landlord banking and rent collection for US property owners",
    "heroSub": "Comparing Revun vs Azibo for landlords who need more than a free US banking account",
    "intro": "Azibo is a US-based landlord platform built around a free FDIC-insured bank account, free rent collection, and free basic accounting for small to mid-sized residential portfolios. Its core appeal is zero monthly cost: landlords pay nothing to collect rent, screen tenants, or track expenses, with revenue coming from optional add-ons and financial products. The platform is positioned squarely at independent US landlords who want a lightweight, bank-first experience and are comfortable working in a browser with no mobile app. Canadian landlords and operators who need built-in communications, AI automation, or a single subscription that replaces every third-party tool will find Azibo's feature set too narrow for their needs.",
    "theirStrengths": [
      "Free core platform with no unit minimums and no monthly subscription, making it genuinely accessible to first-time and small-portfolio landlords.",
      "Purpose-built landlord banking with an FDIC-insured account, high-yield interest, and a cash-back debit card that competitors do not match natively.",
      "Clean, purpose-built real estate accounting with double-entry bookkeeping, Schedule E support, and automated expense categorization at no added cost."
    ],
    "whereRevunWins": [
      {
        "title": "US and Canada in one platform",
        "body": "Azibo is a US-only product. Its banking, ACH rent collection, and state-specific lease templates are built exclusively for American landlords. Revun is designed from the ground up for both the US and Canada, with compliance, currency, and lease tooling that works on both sides of the border. If any of your doors are in Canada, or you plan to expand there, Azibo is a hard stop."
      },
      {
        "title": "Native communications built in",
        "body": "Azibo has no native email, SMS, VoIP, or video layer. Landlords must bolt on separate tools for tenant communication, maintenance coordination, and owner reporting. Revun ships email, SMS, VoIP, and video inside the same subscription, so every conversation is logged, searchable, and tied to the correct property record without a third-party integration."
      },
      {
        "title": "AI automation and a true all-in-one stack",
        "body": "Azibo has acknowledged gaps in maintenance tracking, has no mobile app, and charges separately for collaboration seats, e-signatures, and premium onboarding. Revun includes AI automation, built-in tenant screening, and full accounting under a single flat per-door price with no add-on fees. For a growing portfolio, the Azibo add-on bill compounds quickly, while Revun's cost stays predictable."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "no",
        "note": "US-only. Banking, ACH, and lease templates are US-specific; Canadian landlords cannot use the core product."
      },
      {
        "key": "allinone",
        "competitor": "partial",
        "note": "Free core is solid, but collaboration, e-signatures, and premium onboarding cost extra; no mobile app; no communications layer."
      },
      {
        "key": "comms",
        "competitor": "no",
        "note": "No native email, SMS, VoIP, or video. Landlords must use separate tools for tenant and owner communication."
      },
      {
        "key": "screening",
        "competitor": "yes",
        "note": "Credit, criminal, and eviction reports included; tenant typically pays the per-application fee."
      },
      {
        "key": "ai",
        "competitor": "no",
        "note": "No AI automation features documented on the platform as of mid-2026."
      },
      {
        "key": "pricing",
        "competitor": "partial",
        "note": "Free plan has no unit minimums, which is generous, but add-ons (collaboration seats, e-signatures, onboarding) add up and the model is US-only."
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "Double-entry bookkeeping, automated expense categorization, Schedule E, and rent roll reporting built in at no extra cost."
      },
      {
        "key": "freetier",
        "competitor": "yes",
        "note": "Genuinely free for unlimited units on the core plan; one of the most accessible free tiers in the category."
      }
    ],
    "pricingNote": "Azibo's core platform is free for landlords with unlimited units. Published pricing for optional add-ons starts around $39.99 per tenant screening application, approximately $99 per seat per year for collaboration access, and around $9.99 per lease for e-signatures. These figures reflect publicly listed rates and may change; verify current pricing at azibo.com before making a decision.",
    "bestForThem": "Independent US landlords with a small to mid-sized residential portfolio who want a zero-cost starting point, value a built-in high-yield bank account, and do not need Canadian compliance, native communications, or AI automation.",
    "bestForRevun": "Landlords and property managers operating in both the US and Canada, or those who want email, SMS, VoIP, video, AI automation, tenant screening, and accounting under a single predictable per-door subscription without hunting for add-ons.",
    "migration": "Export your rent roll, lease documents, and transaction history from Azibo as CSV and PDF. Revun's onboarding team maps your unit and tenant records on import, and because Revun's accounting is double-entry from day one, your historical expense data carries over cleanly. Banking transitions require tenant payment method updates, which Revun handles through an automated tenant notification sequence so landlords do not need to chase individual renters.",
    "faqs": [
      {
        "q": "Is Revun a good Azibo alternative?",
        "a": "Yes, especially if you need Canadian compliance, built-in communications (email, SMS, VoIP, video), or AI automation. Azibo's free tier is hard to beat for a basic US portfolio, but once you add collaboration seats, e-signatures, and separate communication tools, Revun's flat per-door pricing often costs less overall while covering significantly more ground."
      },
      {
        "q": "Does Azibo work in Canada?",
        "a": "No. Azibo is a US-only platform. Its bank account is FDIC-insured and US-only, its ACH rent collection requires US bank accounts, and its lease templates are state-specific to the United States. Canadian landlords or anyone with cross-border portfolios need a platform built for both markets, which is exactly what Revun is designed for."
      },
      {
        "q": "Can I migrate from Azibo to Revun?",
        "a": "Yes. You can export your lease documents, tenant records, and transaction history from Azibo and import them into Revun during onboarding. Revun's team walks you through the process, and automated tenant notifications handle the payment method switch so the transition is low-friction for both you and your tenants."
      },
      {
        "q": "How does Revun pricing compare to Azibo?",
        "a": "Azibo's core platform is free, which looks attractive upfront. However, add-ons including collaboration seats (published at around $99 per seat per year), per-lease e-signature fees, and per-applicant screening costs accumulate as your portfolio grows. Revun charges a flat per-door rate with no unit minimums and no add-on fees for communications, screening, or AI tools, making the total cost of ownership more predictable for portfolios beyond a handful of units."
      }
    ]
  },
  "landlord-studio": {
    "slug": "landlord-studio",
    "name": "Landlord Studio",
    "letter": "L",
    "category": "SMB landlord software",
    "tagline": "Revun vs Landlord Studio",
    "heroSub": "How does Landlord Studio compare to Revun for US and Canadian landlords?",
    "intro": "Landlord Studio is a cloud-based property management and accounting platform built for independent landlords and small portfolio investors, typically those managing fewer than 20 units. It earns strong marks for its clean mobile app, receipt scanning, financial reporting, and TransUnion-backed tenant screening. The platform is technically available in Canada but was designed around US workflows, and several features including credit and background checks are not available to Canadian users. Landlords who need an all-in-one platform with native VoIP, video, AI automation, and seamless US plus Canada compliance will find meaningful gaps in what Landlord Studio currently delivers.",
    "theirStrengths": [
      "Best-in-class mobile accounting and receipt scanning: Landlord Studio's OCR-powered Smart Receipt Scan and Schedule E reporting tools are polished and genuinely useful for self-managing landlords at tax time.",
      "Intuitive onboarding for first-time landlords: The platform's interface is consistently praised in independent reviews for being easy to navigate without training, making it a natural starting point for landlords managing their first few units.",
      "AI-assisted rental listings with broad syndication: Landlord Studio auto-generates and syndicates listings to Zillow, Zumper, and Realtor.com from a single dashboard, reducing manual posting work for landlords looking to fill vacancies quickly."
    ],
    "whereRevunWins": [
      {
        "title": "True US and Canada coverage with full feature parity",
        "body": "Revun is built for North American landlords from the ground up. Canadian users get the same tenant screening, payment rails, and compliance tools as US users. Landlord Studio's credit and background checks are unavailable in Canada, and pricing is US-dollar-only, creating friction for any portfolio that spans the border."
      },
      {
        "title": "Native VoIP, video, and SMS in one place with no third-party add-ons",
        "body": "Revun includes email, SMS, VoIP calling, and video conferencing natively inside the platform. Landlord Studio offers basic email and SMS templates but has no built-in calling or video capability and cannot facilitate lead communications or showing bookings through the software. Landlords using Landlord Studio typically stitch together Zoom, Google Voice, or similar tools separately."
      },
      {
        "title": "AI automation and flat per-door pricing with no unit minimums",
        "body": "Revun's AI layer handles routine workflows such as follow-ups, maintenance triage, and lease renewals without manual intervention. Landlord Studio's automation is limited to rent reminders, late-fee application, and OCR receipt entry. On pricing, Revun's flat per-door model scales predictably with no minimums, and units one and two are free. Landlord Studio's per-unit cost structure has drawn user complaints about price increases over time as portfolios grow."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "partial",
        "note": "Available in Canada but credit and background checks do not work for Canadian applicants; bank feeds limited to US, Canada, and UK only"
      },
      {
        "key": "allinone",
        "competitor": "partial",
        "note": "Strong accounting and screening core but no built-in calling, video, or lead-communication tools; relies on external integrations for full workflow"
      },
      {
        "key": "comms",
        "competitor": "partial",
        "note": "Supports email and SMS templates from within the app but has no VoIP, no video, and cannot book showings or communicate with rental leads through the platform"
      },
      {
        "key": "screening",
        "competitor": "partial",
        "note": "TransUnion credit and background checks available for US landlords at an added per-report cost; feature is unavailable for Canadian applicants"
      },
      {
        "key": "ai",
        "competitor": "partial",
        "note": "AI used for listing copy generation, OCR receipt scanning, and bank-feed categorization; no broader AI automation for lease workflows, maintenance triage, or tenant communications"
      },
      {
        "key": "pricing",
        "competitor": "partial",
        "note": "Published pricing starts around $12 per month billed annually for up to four units; per-unit fees stack on top and have increased over time according to user reviews; no truly unlimited or flat-rate tier"
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "Built-in double-entry accounting, Schedule E reporting, bank feeds, and Xero integration are genuine strengths and a primary reason landlords choose the platform"
      },
      {
        "key": "freetier",
        "competitor": "yes",
        "note": "GO plan is free for the first three units, which is competitive for micro-landlords just getting started"
      }
    ],
    "pricingNote": "Landlord Studio published pricing starts around $12 per month (billed annually) for its PRO plan covering the first few units, with per-unit fees added beyond that threshold. A free tier covers up to three units. Pricing has reportedly increased since the platform launched; confirm current rates directly with Landlord Studio before budgeting.",
    "bestForThem": "Landlord Studio is a good fit for US-based individual landlords managing fewer than 20 residential units who prioritize clean accounting, mobile receipt tracking, and Schedule E tax prep, and who do not need built-in calling, video, or cross-border Canadian compliance.",
    "bestForRevun": "Revun is the stronger choice for landlords and property managers who operate across the US and Canada, need native VoIP and video without add-ons, want AI to handle routine follow-ups and workflows, or are scaling a portfolio where flat per-door pricing and free access for small portfolios lower the cost of entry.",
    "migration": "Landlord Studio allows full data export to Excel from the PRO plan. Revun's onboarding team can import tenant records, lease terms, payment histories, and expense logs from that export. Most landlords complete the switch in under a week. Canadian users migrating from Landlord Studio will gain tenant screening and payment features that were not previously available to them.",
    "faqs": [
      {
        "q": "Is Revun a good Landlord Studio alternative?",
        "a": "Revun is a strong alternative to Landlord Studio for landlords who need more than accounting and basic messaging. Revun adds native VoIP, video, AI-driven workflow automation, and full US plus Canada feature parity in a single platform. Landlord Studio is still a competitive pick if your primary need is mobile-first accounting and you manage a small US-only portfolio."
      },
      {
        "q": "Does Landlord Studio work in Canada?",
        "a": "Landlord Studio is available in Canada and Canadian users can access the app, but several core features are restricted. Tenant credit and background checks through TransUnion are not available to Canadian landlords, and pricing is billed in US dollars only. Revun was built for both markets and delivers the same screening, payments, and compliance tools to US and Canadian users."
      },
      {
        "q": "Can I migrate from Landlord Studio to Revun?",
        "a": "Yes. Landlord Studio's PRO and PRO+ plans include a full data export to Excel. Revun's onboarding team accepts that export and maps tenant profiles, lease data, payment history, and expense records into your new account. Most migrations are completed within a week with no data loss."
      },
      {
        "q": "How does Revun pricing compare to Landlord Studio?",
        "a": "Landlord Studio published pricing starts around $12 per month (billed annually) for a base set of units, with per-unit fees added as your portfolio grows. Revun uses flat per-door pricing with no unit minimums and is free for landlords with one or two units. For larger portfolios the predictable per-door rate on Revun typically comes out ahead of Landlord Studio's stacking per-unit model."
      }
    ]
  },
  "simplifyem": {
    "slug": "simplifyem",
    "name": "SimplifyEm",
    "letter": "S",
    "category": "SMB landlord software",
    "tagline": "Straightforward US landlord accounting at a low entry price",
    "heroSub": "Comparing Revun vs SimplifyEm for US and Canadian landlords who want more than bookkeeping",
    "intro": "SimplifyEm is a US-based property management platform founded in 2006 that has built a loyal following among solo landlords and small-portfolio investors who want solid accounting tools without a steep learning curve. It covers the essentials well: rent collection, lease management, expense tracking, and basic tenant screening available as a pay-per-use add-on. The platform is best suited to independent landlords managing fewer than 100 US residential units who prioritize accounting accuracy and affordability over advanced communications or automation features. Landlords managing Canadian properties, or those who need native VoIP, AI-assisted workflows, or a fully bundled platform, will find meaningful gaps.",
    "theirStrengths": [
      "Flat same-features-across-tiers model means small landlords get access to every accounting and reporting tool without paying for a higher plan",
      "Long-standing platform with over 150,000 users and a well-documented track record of reliable US-focused bookkeeping, IRS-ready expense categorization, and tax support",
      "Low published entry price and a no-credit-card 15-day free trial make it easy to evaluate with no financial commitment"
    ],
    "whereRevunWins": [
      {
        "title": "North American coverage out of the box",
        "body": "SimplifyEm was built for the US market. Canadian landlords using it have reported issues with Ontario lease forms, provincial compliance gaps, and the inability to call US support lines from a Canadian phone plan without paying international rates. Revun is designed from the ground up for both US and Canadian jurisdictions, with localized lease templates, compliance tooling, and support that does not require a cross-border workaround."
      },
      {
        "title": "Native communications stack included",
        "body": "SimplifyEm has no built-in VoIP, SMS broadcast, or video calling. Landlords who want to reach tenants by phone or text must bolt on separate tools and manually reconcile conversations. Revun ships email, SMS, VoIP, and video in a single inbox tied directly to tenant records, so every communication is logged without a third-party integration."
      },
      {
        "title": "AI automation and bundled screening at no per-transaction cost",
        "body": "SimplifyEm charges per screening report (published pricing starts around $19.95 per applicant) and has no meaningful AI automation layer. Ninety percent of reviews on G2 flag automation as a weakness. Revun includes AI-assisted workflows and tenant screening as part of the platform subscription, meaning landlords with high turnover do not face escalating per-transaction costs as their portfolio grows."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "partial",
        "note": "Built for the US; Canadian landlords report provincial lease gaps and cross-border support friction"
      },
      {
        "key": "allinone",
        "competitor": "partial",
        "note": "Core accounting and lease tools included, but screening, listings, and applications cost extra per use"
      },
      {
        "key": "comms",
        "competitor": "no",
        "note": "No built-in VoIP, SMS, or video; landlords must use separate tools for tenant communications"
      },
      {
        "key": "screening",
        "competitor": "partial",
        "note": "Screening available as a pay-per-report add-on (published pricing starts around $19.95 per applicant), not bundled"
      },
      {
        "key": "ai",
        "competitor": "no",
        "note": "No AI automation layer; reviewer data consistently flags automation as a platform weakness"
      },
      {
        "key": "pricing",
        "competitor": "partial",
        "note": "Per-unit tiers with a low entry price, but annual billing locks in the cost and add-ons accumulate for active landlords"
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "Strong US-focused accounting with IRS expense categorization, bank reconciliation, and owner reporting across all tiers"
      },
      {
        "key": "freetier",
        "competitor": "no",
        "note": "No permanent free tier; offers a 15-day free trial only before requiring a paid subscription"
      }
    ],
    "pricingNote": "SimplifyEm published pricing starts around $35 per month for up to 5 units on a monthly plan, with annual plans reducing that figure meaningfully. Add-on costs for tenant screening, rental applications, and lease forms are billed separately per use. Verify current rates directly with SimplifyEm before making a purchasing decision.",
    "bestForThem": "Independent US landlords managing fewer than 50 units who want proven bookkeeping, IRS-ready reporting, and a familiar interface at a predictable monthly cost, and who do not need built-in communications or Canadian compliance support.",
    "bestForRevun": "Landlords and small property managers operating in both the US and Canada, or US-only portfolios where tenant communications, AI-assisted workflows, and bundled screening matter more than standalone accounting depth.",
    "migration": "SimplifyEm stores tenant records, lease data, and financial history that can be exported from its reporting module as CSV or PDF files. Revun's onboarding team can ingest exported rent rolls, tenant contact lists, and historical transaction data so that your accounting history carries over and tenants receive portal invitations on day one. Most landlords moving from SimplifyEm complete the switch in under a week.",
    "faqs": [
      {
        "q": "Is Revun a good SimplifyEm alternative?",
        "a": "Yes, particularly if you manage properties in Canada, want communications (email, SMS, VoIP, and video) built into the same platform, or want tenant screening bundled rather than billed per applicant. SimplifyEm has strong US accounting, but Revun covers a broader feature set without add-on fees stacking up as your portfolio grows."
      },
      {
        "q": "Does SimplifyEm work in Canada?",
        "a": "SimplifyEm is primarily built for the US market. Canadian landlords have reported gaps in provincial lease templates (notably Ontario), and support is delivered via US phone lines that require international calling from Canada. Revun is built for both US and Canadian jurisdictions from the start."
      },
      {
        "q": "Can I migrate from SimplifyEm to Revun?",
        "a": "Yes. Export your tenant data, lease records, and financial history from SimplifyEm and Revun's onboarding team will help you import it. Most landlords complete the migration in less than a week with no gap in rent collection or tenant access."
      },
      {
        "q": "How does Revun pricing compare to SimplifyEm?",
        "a": "SimplifyEm published pricing starts around $35 per month for up to 5 units, with add-ons charged separately for screening, applications, and lease forms. Revun uses flat per-door pricing with no unit minimums and is free for 1 to 2 units, so landlords with active tenant turnover typically pay less in total once add-on costs are factored in."
      }
    ]
  },
  "rentvine": {
    "slug": "rentvine",
    "name": "Rentvine",
    "letter": "R",
    "category": "PM software for managers",
    "tagline": "Professional-grade PM software built for US property management companies",
    "heroSub": "Comparing Revun vs Rentvine for property managers in the US and Canada",
    "intro": "Rentvine is a cloud-based property management platform aimed squarely at professional PM companies rather than independent landlords. It ships trust accounting, leasing automation, maintenance coordination, and an AI assistant under one subscription with no feature paywalls. Published pricing starts around $2.50 per unit per month with a roughly $199 monthly minimum, plus a one-time onboarding fee, making it most cost-effective once a portfolio crosses roughly 80 doors. The platform is US-centric, with no documented Canadian compliance layer, and does not offer a mobile app or a free tier for small owners.",
    "theirStrengths": [
      "Trust accounting depth: Rentvine ships fully customizable owner statements, an open RESTful API, and a financial analyst during onboarding, giving mid-to-large US PM firms a robust back-office from day one.",
      "All-inclusive feature set with no paywalls: every plan tier unlocks the full feature set including RentScreener tenant screening powered by TransUnion and Plaid, digital signatures via RentSign, and built-in AI task automation.",
      "Highly rated US-based customer support: reviewers consistently flag a sub-40-minute average response time, a staffed onboarding specialist, and a detailed knowledge base as standout advantages over legacy competitors."
    ],
    "whereRevunWins": [
      {
        "title": "North American coverage out of the box",
        "body": "Revun is built for both the US and Canada from the ground up, with compliance workflows, lease frameworks, and currency handling for both markets. Rentvine is US-focused, and Canadian managers using it must work around gaps in provincial compliance, making Revun the clear choice for any portfolio that crosses the border."
      },
      {
        "title": "Native communication stack at no extra cost",
        "body": "Revun bundles email, SMS, VoIP, and video into the core platform so every owner, tenant, and vendor interaction lives in one thread with no third-party integration required. Rentvine relies on external tools for voice and video, adding cost and context-switching for teams that handle high communication volume."
      },
      {
        "title": "Free tier and no monthly minimum",
        "body": "Revun is free for portfolios of one or two units and carries no monthly floor, letting solo owners and small-portfolio managers get started without a financial commitment. Rentvine's roughly $199 monthly minimum means smaller operators are paying for capacity they may not need for years, a real barrier to entry that Revun removes entirely."
      }
    ],
    "matrix": [
      {
        "key": "na",
        "competitor": "no",
        "note": "US-focused platform; no documented Canadian compliance layer or provincial lease support"
      },
      {
        "key": "allinone",
        "competitor": "yes",
        "note": "Full feature set on every plan with no paywalled add-ons; accounting, screening, and AI all included"
      },
      {
        "key": "comms",
        "competitor": "partial",
        "note": "Tenant and owner portals plus messaging included; no native VoIP or video, relies on external tools"
      },
      {
        "key": "screening",
        "competitor": "yes",
        "note": "RentScreener via TransUnion and Plaid is built in with no separate subscription required"
      },
      {
        "key": "ai",
        "competitor": "partial",
        "note": "AI assistant handles voice and text commands for reports and tasks, but scope is narrower than a full automation layer"
      },
      {
        "key": "pricing",
        "competitor": "partial",
        "note": "Flat per-unit rate with no feature tiers, but a roughly $199 monthly minimum makes it expensive for small portfolios"
      },
      {
        "key": "accounting",
        "competitor": "yes",
        "note": "Built-in trust accounting with fully customizable owner statements and a financial analyst during onboarding"
      },
      {
        "key": "freetier",
        "competitor": "no",
        "note": "No free tier; monthly minimum applies from the first door billed"
      }
    ],
    "pricingNote": "Rentvine's published pricing starts around $2.50 per unit per month with a monthly minimum in the range of $199, plus a one-time onboarding fee. These figures reflect rates reported across third-party review platforms as of mid-2026 and may change; check Rentvine's pricing page for current numbers before budgeting.",
    "bestForThem": "Rentvine fits established US property management companies with 80 or more doors that want deep trust accounting, a fully loaded feature set from day one, and are willing to pay a meaningful monthly floor for the setup support and financial analyst included in onboarding.",
    "bestForRevun": "Revun is the stronger fit for managers who operate or plan to operate in both the US and Canada, owners starting with a small portfolio who cannot justify a $199 monthly floor, and teams that want native voice, SMS, and video communication without bolting on a separate telephony tool.",
    "migration": "Rentvine includes active data migration as part of its paid onboarding package, so your existing data is not locked in. Revun's import tools accept standard CSV exports covering tenant records, lease terms, payment history, and owner contacts. Most teams complete the transition in two to four weeks, and Revun support walks you through the mapping at no additional charge.",
    "faqs": [
      {
        "q": "Is Revun a good Rentvine alternative?",
        "a": "Yes, particularly if you manage properties in Canada, run a smaller portfolio under 80 doors, or want native VoIP and video communication without a third-party add-on. Rentvine is strong for established US PM firms with larger portfolios, but Revun's flat per-door pricing, free tier, and North American compliance coverage make it a compelling alternative for a broader range of managers."
      },
      {
        "q": "Does Rentvine work in Canada?",
        "a": "Rentvine is designed for the US market and does not document Canadian provincial compliance, CAD currency handling, or Canadian lease frameworks. Canadian property managers who use Rentvine typically work around these gaps manually. Revun is built for both the US and Canada from the start, making it the more practical choice for cross-border or Canada-based portfolios."
      },
      {
        "q": "Can I migrate from Rentvine to Revun?",
        "a": "Yes. Rentvine provides data exports as part of its offboarding process, and Revun's onboarding team supports CSV imports for tenant records, leases, payment history, and owner contacts. Most managers complete the migration in two to four weeks with no manual re-entry of core financial records."
      },
      {
        "q": "How does Revun pricing compare to Rentvine?",
        "a": "Rentvine's published pricing starts around $2.50 per unit per month with a monthly minimum in the range of $199, meaning smaller portfolios effectively pay above-market rates per door. Revun uses flat per-door pricing with no monthly minimum and offers a free tier for one to two units, so you pay only for what you actually manage at every stage of portfolio growth."
      }
    ]
  }
}
